model: 'srresnet'

## parameters for srresnet
scale: 4
colors: 3
range: 1
num_feat: 64
num_block: 16
pretrain:

## parameters for multi-objective optimization
popsize: 10
neighborsize: 1
cro: SBX
mut: simple
sel: non_dom
pCrossover: 0.9
pMutation: 0.3
mu: 0.02

## parameters for loss function
perceptual_opt:
  layer_weights:
    'conv5_4': 1 # before relu
  vgg_type: vgg19
  use_input_norm: true
  range_norm: false
  perceptual_weight: 1.0
  style_weight: 0
  criterion: l1

## parameters for model training
patch_size: 128
batch_size: 16
batch_size_EA: 1
data_repeat: 1
data_augment: 1

is_qat: 0
epochs: 500
EA_iter_epoch: 6400
adam_init_epochs: 500
adam_epoch: 500
EA_epoch: 1
lr: !!float 1e-4
decays: [500]
gamma: 0.5
log_every: 100
test_every: 1
log_path: "./experiments"
log_name: 'test_tch_ssim_mullr'

## hardware specification
gpu_ids: [0]
threads: 8

## data specification
training_data_path: ['/Flickr2K/Flickr2K_HR',
                      '/Flickr2K/Flickr2K_LR_bicubic/X4'] #[HR, LR]
                  
eval_sets:  
  names: ['Set5', 'Set14', 'B100', 'Urban100', 'Manga109']
  HR_paths: ['/Set5/GTmod12',
              '/Set14/GTmod12',
              '/B100/HR',
              '/Urban100/GTmod12',
              '/Manga109/HR',]
  LR_paths: ['/Set5/LRbicx4',
              '/Set14/LRbicx4',
              '/B100/LR_bicubic/X4',
              '/Urban100/LRbicx4',
              '/Manga109/LR_bicubic/X4',]
fusion_sets:  
  names: ['div2k']
  HR_paths: ['/DIV2K/DIV2K_train_HR']
  LR_paths: ['/DIV2K/DIV2K_train_LR_bicubic/X4']