model: 'swinIR'
## parameters for swinIR
scale: 4
colors: 3
n_resblocks: 16
n_feats: 64
res_scale: 1.0
rgb_range: 1.0
range: 1
pretrain: null

## parameters for multi-objective optimization
popsize: 5
neighborsize: 1
cro: SBX
mut: simple
sel: non_dom
pCrossover: 0.9
pMutation: 0.2
mu: 0.02
num_EA_data: 400
batch_size_EA: 1
ema_decay: 0.999

## parameters for loss function
perceptual_opt:
  layer_weights:
    'conv1_2': 0.1
    'conv2_2': 0.1
    'conv3_4': 1
    'conv4_4': 1
    'conv5_4': 1 # before relu
  vgg_type: vgg19
  use_input_norm: true
  range_norm: false
  perceptual_weight: 1.0
  style_weight: 0
  criterion: l1

## parameters for GAN loss
network_d:
  type: VGGStyleDiscriminator
  num_in_ch: 3
  num_feat: 64

gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0

img_size: 64
patch_size: 128
p_size: 1
mlp_ratio: 2
embed_dim: 60
num_heads: [6, 6, 6, 6]
depths: [6, 6, 6, 6]
window_size: 8
qkv_bias: True
drop_rate: 0.
attn_drop_rate: 0.
drop_path_rate: 0.1
ape: False
patch_norm: True
use_checkpoint: False
## parameters for model training
batch_size: 16
data_repeat: 32
data_augment: 1
batch_size_EA: 1
upsampler: 'pixelshuffledirect'

is_qat: 0
epochs: 250
adam_epoch: 251
# 10
EA_iter_per_epoch: 200
EA_epoch: 1
lr: !!float 2e-4
decays: [50, 100, 150, 200]
gamma: 0.5
store_in_ram: 0
log_every: 100
test_every: 5
log_path: "./experiments"
log_name: 'test'

## hardware specification
gpu_ids: [0]
threads: 4

## data specification
training_data_path: ['/Flickr2K/Flickr2K_HR',
                      '/Flickr2K/Flickr2K_LR_bicubic/X4'] #[HR, LR]
                  
eval_sets:  
  names: ['Set5', 'Set14', 'B100', 'Urban100', 'Manga109']
  HR_paths: ['/Set5/GTmod12',
              '/Set14/GTmod12',
              '/B100/HR',
              '/Urban100/GTmod12',
              '/Manga109/HR',]
  LR_paths: ['/Set5/LRbicx4',
              '/Set14/LRbicx4',
              '/B100/LR_bicubic/X4',
              '/Urban100/LRbicx4',
              '/Manga109/LR_bicubic/X4',]
fusion_sets:  
  names: ['div2k']
  HR_paths: ['/DIV2K/DIV2K_train_HR']
  LR_paths: ['/DIV2K/DIV2K_train_LR_bicubic/X4']